# Generated by Django 5.1.9 on 2025-12-15 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10, verbose_name='縣市')),
                ('town', models.CharField(max_length=10, verbose_name='行政區')),
                ('street', models.CharField(max_length=100, verbose_name='街道/路名')),
                ('house_type', models.CharField(max_length=50, verbose_name='房屋類型')),
                ('house_age', models.FloatField(default=0, verbose_name='屋齡')),
                ('total_floors', models.FloatField(default=0, verbose_name='總樓層')),
                ('floor_number', models.FloatField(default=0, verbose_name='所在樓層')),
                ('floor_area', models.FloatField(default=0, verbose_name='建坪')),
                ('land_area', models.FloatField(default=0, verbose_name='地坪')),
                ('room_count', models.IntegerField(default=0, verbose_name='房間數')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='預估總價(萬)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='預估單價(萬/坪)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('nearby_data', models.JSONField(blank=True, default=list, verbose_name='周邊實價資訊快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('is_favorite', models.BooleanField(default=True, verbose_name='是否收藏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '估價收藏紀錄',
                'verbose_name_plural': '估價收藏紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
