# Generated by Django 5.1.9 on 2025-11-04 14:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房屋中介名稱')),
                ('city', models.CharField(max_length=50, verbose_name='分行所在縣市')),
                ('town', models.CharField(max_length=50, verbose_name='分行所在行政區')),
            ],
            options={
                'verbose_name': '房屋中介',
                'verbose_name_plural': '房屋中介',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('occup', models.TextField(blank=True, verbose_name='職業')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='國籍')),
            ],
            options={
                'verbose_name': '買家',
                'verbose_name_plural': '買家',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('house_type', models.CharField(max_length=100, verbose_name='房屋類型')),
                ('total_price', models.IntegerField(verbose_name='總價（萬/坪）')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='建立檔案時間')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='house.agent', verbose_name='房屋中介')),
                ('buyers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='house.buyer', verbose_name='買家')),
            ],
            options={
                'verbose_name': '房屋資訊',
                'verbose_name_plural': '房屋資訊',
            },
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='縣市')),
                ('town', models.CharField(blank=True, max_length=200, null=True, verbose_name='行政區')),
                ('house_age', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='屋齡（年）')),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='建坪')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='地坪')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='單價（萬/坪）')),
                ('sold_time', models.DateField(default=datetime.date.today, verbose_name='出售日期')),
                ('description', models.TextField(blank=True, verbose_name='房屋簡介')),
                ('house_image', models.ImageField(blank=True, null=True, upload_to='house_images/', verbose_name='房屋圖片')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='house.house', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '房屋詳細資料',
                'verbose_name_plural': '房屋詳細資料',
            },
        ),
    ]
