# Generated by Django 5.1.9 on 2025-12-02 16:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仲介姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='電子郵件')),
                ('company', models.CharField(blank=True, help_text='例如：oo房屋', max_length=100, verbose_name='隸屬公司')),
                ('branch', models.CharField(blank=True, help_text='例如：三峽店', max_length=100, verbose_name='分行名稱')),
                ('city', models.CharField(max_length=50, verbose_name='分行所在縣市')),
                ('town', models.CharField(max_length=50, verbose_name='分行所在行政區')),
            ],
            options={
                'verbose_name': '房屋仲介',
                'verbose_name_plural': '房屋仲介',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='買家姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='電子郵件')),
            ],
            options={
                'verbose_name': '買家',
                'verbose_name_plural': '買家',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('house_type', models.CharField(max_length=100, verbose_name='房屋類型')),
                ('total_price', models.IntegerField(verbose_name='總價格（萬元）')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='建立檔案時間')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='house.agent', verbose_name='仲介')),
                ('buyers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='house.buyer', verbose_name='買家')),
            ],
            options={
                'verbose_name': '房屋資訊',
                'verbose_name_plural': '房屋資訊',
            },
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='縣市')),
                ('town', models.CharField(max_length=200, verbose_name='行政區')),
                ('house_age', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='屋齡（年）')),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='建坪')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='地坪')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='建坪單價（萬元/坪）')),
                ('floor_number', models.IntegerField(verbose_name='所在層數')),
                ('total_floors', models.IntegerField(verbose_name='地上總層數')),
                ('room_count', models.IntegerField(verbose_name='房間數')),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='經度')),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='緯度')),
                ('sold_time', models.DateField(verbose_name='出售日期')),
                ('house_image', models.ImageField(blank=True, null=True, upload_to='house_images/', verbose_name='圖片')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='house.house', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '房屋詳細資料',
                'verbose_name_plural': '房屋詳細資料',
            },
        ),
    ]
