# Generated by Django 5.1.9 on 2025-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='sold_time',
            field=models.DateField(verbose_name='出售日期'),
        ),
    ]
