# Generated by Django 5.1.9 on 2025-11-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_housedetail_sold_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housedetail',
            name='description',
        ),
    ]
