# Generated by Django 5.1.9 on 2025-12-03 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_merge_house_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '房屋資訊', 'verbose_name_plural': '房屋資訊'},
        ),
        migrations.AlterField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses_sold', to='house.agent', verbose_name='仲介'),
        ),
        migrations.AlterField(
            model_name='house',
            name='buyers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses_bought', to='house.buyer', verbose_name='買家'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterModelTable(
            name='house',
            table='house_house',
        ),
        migrations.DeleteModel(
            name='HouseDetail',
        ),
    ]
