# Generated by Django 5.1.9 on 2025-11-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_remove_housedetail_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': '房屋仲介', 'verbose_name_plural': '房屋仲介'},
        ),
        migrations.AddField(
            model_name='agent',
            name='branch',
            field=models.CharField(blank=True, help_text='例如：大安店', max_length=100, verbose_name='分行名稱'),
        ),
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.CharField(blank=True, help_text='例如：信義房屋、永慶房屋', max_length=100, verbose_name='隸屬公司'),
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='電子郵件'),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='仲介姓名'),
        ),
    ]
