# Generated by Django 5.1.9 on 2025-11-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_alter_agent_options_agent_branch_agent_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='budget',
            field=models.IntegerField(blank=True, help_text='單位：萬', null=True, verbose_name='預算 (萬)'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='電子郵件'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='需求備註'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='聯絡電話'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '潛在客戶'), ('INACTIVE', '暫不考慮'), ('CLOSED', '已成交')], default='ACTIVE', max_length=10, verbose_name='客戶狀態'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='買家姓名'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='occup',
            field=models.CharField(blank=True, max_length=100, verbose_name='職業'),
        ),
    ]
