# Generated by Django 5.1.9 on 2025-11-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_buyer_budget_buyer_email_buyer_notes_buyer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='occup',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='status',
        ),
    ]
