# Generated by Django 5.1.9 on 2025-11-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_remove_buyer_birth_date_remove_buyer_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='branch',
            field=models.CharField(blank=True, help_text='例如：三峽店', max_length=100, verbose_name='分行名稱'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.CharField(blank=True, help_text='例如：oo房屋', max_length=100, verbose_name='隸屬公司'),
        ),
        migrations.AlterField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='house.agent', verbose_name='房屋仲介'),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_price',
            field=models.IntegerField(verbose_name='總價格（萬/坪）'),
        ),
        migrations.AlterField(
            model_name='housedetail',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/', verbose_name='圖片'),
        ),
    ]
